### ISSUE TITLE
`impg` should check if my input PAF changed to rebuild the index

### ISSUE THREAD

**Issue by subwaystation** [pangenome/impg#11]
When I played around like in https://github.com/pangenome/impg/issues/10, I realized that when I re-created the PAF with a different wfmash command, I had to rebuild the `impg` index. But there was no warning or error. This might confuse users.
*Maybe* we can embed a kind of sha256 sum or md5 sum in the header of the `impg` index? 
I am aware that for large PAFs with several hundred Gs this might be a waste of time. Not sure. What do you think?

**Comment by AndreaGuarracino** [comment]
I've encountered the same problem multiple times, but I'm not sure if we should link the index to the PAF, if the link is expensive. I've had similar issues with the FASTA index, but that's true that the FASTA is more stable than a PAF file

**Comment by bkille** [comment]
We could also do something thats not as robust but at least warns users. i.e. we could store the last modification date of the PAF file in the index, and warn the user if the PAF file has been modified since the index creation. 

There will probably be some false alarms, but its cheap and would catch the case where the PAF file changes.

**Comment by subwaystation** [comment]
:100:

**Comment by AndreaGuarracino** [comment]
I like that. I've seen something similar, maybe with the BAM index, which complains if you download the index before the BAM file, so the BAM file becomes more recent than the index file.

Please go for it!

**Comment by AndreaGuarracino** [comment]
So, the first step can be just 'read the timestamps of both PAF and index and emit a warning if the index is older than the PAF'. Let's see how many issues this will prevent. This way the index stays clean.

**Comment by subwaystation** [comment]
this issue cost me again 1 hour

**Comment by subwaystation** [comment]
but you are on it @bkille, this is amazing!
