### ISSUE TITLE
Cool project and question

### ISSUE THREAD

**Issue by rob-p** [pangenome/impg#5]
This is a very cool project! There is a use-case for which we often have a need, and I wonder if it's enabled by `impg`.  

Say I have an a collection of (RNA-seq) reads aligned against the genome (including spliced alignments), and likewise an annotation for this genome describing the known transcripts.  I'd like to "project" the genomic alignments against the transcriptome.  In general this is a one-to-many projection, as one genomic locus may often overlap many alternatively-spliced transcript isoforms.

This capability is built into STAR — it can output both genomic and transcriptomic alignments at once. However, I'm not aware of other aligners (e.g. HISAT2) that have this capability.  Likewise, STAR doesn't expose it as independent functionality, but just a flag during normal operation.  

However, having such capability would be very useful in general (as would going the other way from transcriptomic to genomic coordinates).

Is this something that `impg` can do, or that it might be possible to make `impg` do?

Thanks!
Rob

**Comment by AndreaGuarracino** [comment]
If you create a PAF file by aligning the transcriptome (your query) against the genome (your target), you can use it to project any genome range onto the transcriptome.
________________________________
From: Rob Patro ***@***.***>
Sent: Saturday, April 13, 2024 16:17
To: ekg/impg ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ekg/impg] Cool project and question (Issue #5)


This is a very cool project! There is a use-case for which we often have a need, and I wonder if it's enabled by impg.

Say I have an a collection of (RNA-seq) reads aligned against the genome (including spliced alignments), and likewise an annotation for this genome describing the known transcripts. I'd like to "project" the genomic alignments against the transcriptome. In general this is a one-to-many projection, as one genomic locus may often overlap many alternatively-spliced transcript isoforms.

This capability is built into STAR — it can output both genomic and transcriptomic alignments at once. However, I'm not aware of other aligners (e.g. HISAT2) that have this capability. Likewise, STAR doesn't expose it as independent functionality, but just a flag during normal operation.

However, having such capability would be very useful in general (as would going the other way from transcriptomic to genomic coordinates).

Is this something that impg can do, or that it might be possible to make impg do?

Thanks!
Rob
